Object.defineProperty(exports, "__esModule", { value: true });
exports.GET_STATE = exports.DELETE_CALLBACK = exports.CREATE_CALLBACK = exports.STATE_CLEAR = exports.STATE_DELETE = exports.SET_STATE_REPLACE = exports.SET_STATE = exports.SET_STATE_KEY_MAP = void 0;
exports.SET_STATE_KEY_MAP = 'SET_STATE_KEY_MAP';
exports.SET_STATE = 'SET_STATE';
exports.SET_STATE_REPLACE = 'SET_STATE_REPLACE';
exports.STATE_DELETE = 'STATE_DELETE';
exports.STATE_CLEAR = 'STATE_CLEAR';
exports.CREATE_CALLBACK = 'CREATE_CALLBACK';
exports.DELETE_CALLBACK = 'DELETE_CALLBACK';
exports.GET_STATE = 'GET_STATE';
